# Generated by Django 6.0.1 on 2026-01-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_created=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('pay_with', models.CharField(choices=[('card', 'Karta orqali'), ('summ', 'Naqd pul orqali')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_trend', models.BooleanField(default=False)),
                ('is_cheaper', models.BooleanField(default=False)),
                ('is_expensive', models.BooleanField(default=False)),
                ('in_top', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_original', models.BooleanField(default=True)),
                ('top_deliveried', models.BooleanField(default=True)),
                ('colour', models.CharField(choices=[('brown', 'Jigar rang'), ('red', 'Qizil rang'), ('green', 'Yashil rang'), ('blue', "Ko'k rang"), ('black', 'Qora rang'), ('white', 'Oq rang'), ('golden', 'Oltin rang')], max_length=100)),
                ('brand', models.CharField(choices=[('adidas', 'Adidas'), ('nike', 'Nike'), ('chanel', 'Chanel'), ('gucci', 'Gucci'), ('prada', 'Prada')], max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ForMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erkaklar_uchun', models.BooleanField()),
                ('ayollar_uchun', models.BooleanField()),
                ('bolalar_uchun', models.BooleanField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.basket')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.filter')),
            ],
        ),
    ]
